### ISSUE TITLE
some more info...on functionality basics 

### ISSUE THREAD

**Issue by jordila** [EthanMcBloxxer/jekyll-theme-mastodon#4]
Hi @EthanMcBloxxer , just re-reading 'Background' section ...

Does it mean this project can act as a kind of Mastodon (full instance) - frontend... somehow ? or may have i dreamed it ?

I mean,,... what i would love to see is a (micro)blog theme that would automatically post in my (backend) Mastodon instance. Would such a workflow be possible here ?

---

PS: I know i fediverse someone succeeded in integrating the different puzzle pieces... as a Jekyll 'comments' system

**Comment by EthanMcBloxxer** [comment]
Not really. It only appears like Mastodon, but really uses [Jekyll](https://jekyllrb.com/) as the generator for the site. It has no interaction with the fediverse or real Mastodon. It's mostly supposed to be a replacement or look-alike for hosting your own instance of Mastodon on a server / VPS, as GitHub Pages is free.

You might be able to make some sort of program that copies posts from a real Mastodon instance (through their [API](https://docs.joinmastodon.org/client/intro/)) and makes them inside the theme's repository through either a program or GitHub Actions, and there may be many more things you could make using this theme. Those just aren't already made.
